run:
  timeout: 10m
  modules-download-mode: vendor

linters:
  enable:
    - gofmt
    - govet
    - depguard
    - goimports
    - ineffassign
    - misspell
    - unused
    - revive
    - staticcheck
    - typecheck
  disable-all: true

linters-settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: "io/ioutil"
            desc: The io/ioutil package has been deprecated. See https://go.dev/doc/go1.16#ioutil

issues:
  exclude-rules:
    - linters:
        - revive
      text: "stutters"
